import 'reset-css';

import type { Metadata } from 'next';
import { Bai_Jamjuree } from 'next/font/google';

import '../styles/core/global.scss';
import Pane from '@/components/layout/pane';
import SideBar from '@/components/sidebar/sidebar';

const bai_jamjuree = Bai_Jamjuree({
  weight: ['400', '600'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={bai_jamjuree.className}>
        <Pane>
          <aside>
            <SideBar />
          </aside>
          <main>
            <p>main conten</p>
            {children}
          </main>
        </Pane>
      </body>
    </html>
  );
}
